// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","id":"1"},"2":{"path":"/home","id":"2"},"3":{"path":"/agent","id":"3"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home" */'@/pages/Home.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Agent" */'@/pages/Agent.tsx')),
},
  };
}
